# packages ------------------------------------------------------------------------------------
library(gridExtra)
library(grid)


# plot function -------------------------------------------------------------------------------
plot.matheaufgabe <- function(x, y, base_size = 20, ...){
  # x: list of exercises generated by generate_exercise_list()
  # y: number of chunks to use
  if(missing(y)) y <- 4

  N <- length(x)

  tt1 <- ttheme_minimal(base_size = base_size, core=list(fg_params=list(hjust=1, x=0.9)))
  g1 <- tableGrob(x[1:(N/y)], theme = tt1)
  g2 <- tableGrob(x[(N/y + 1):(2*N/y)], theme = tt1)
  g3 <- tableGrob(x[(2*N/y + 1):(3*N/y)], theme = tt1)
  g4 <- tableGrob(x[(3*N/y + 1):(4*N/y)], theme = tt1)
  grid.arrange(g1, g2, g3, g4, layout_matrix = matrix(c(1, 1, NA, 2, 2, 
                                                        1, 1, NA, 2, 2, 
                                                        rep(NA, 5), 
                                                        3, 3, NA, 4, 4,
                                                        3, 3, NA, 4, 4
  ), nr = 5, byrow = T))
}

